stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-nuxt:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:16.19.0-bullseye
  script:
    - mkdir -p truffle-project/build/contracts
    - echo "{}" > truffle-project/build/contracts/AddProject.json
    - echo "{}" > truffle-project/build/contracts/Donate.json
    - echo "{}" > truffle-project/build/contracts/Vote.json
    - cd nuxt
    - npm install
    - npm run build

build-truffle:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:16.19.0-bullseye
  script:
    - cd truffle-project
    - npm install -g truffle
    - truffle compile
    
    

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: node:16.19.0-bullseye
  script:
    - cd truffle-project
    - npm install -g truffle
    - npm install truffle-assertions
    - truffle compile
    - truffle test
